version: "3.8"

services:
  frontend:
    env_file: ".env"
    image: ghcr.io/JohnTwiiX/conduit-frontend:latest
    container_name: conduit-frontend
    ports:
      - "8084:80"
    restart: on-failure

  backend:
    env_file: ".env"
    image: ghcr.io/JohnTwiiX/conduit-backend:latest
    container_name: conduit-backend
    volumes:
      - conduit-db:/app/conduit/db.sqlite3
    ports:
      - "8085:8000"
    restart: on-failure

volumes:
  conduit-db:
