name: Main Repository Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_main_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the main repository
        uses: actions/checkout@v3

  pull_or_clone_repository:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into the server and deploy the main repository
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Define project directory on the server
            PROJECT_DIR=${{ secrets.PROJECT_PATH }}

            # Clone the main repo if not already cloned, otherwise pull the latest changes
            cd $PROJECT_DIR || git clone https://github.com/JohnTwiiX/Conduit-Container.git $PROJECT_DIR
            cd $PROJECT_DIR

            # Pull the latest changes from the main branch
            git pull origin main

            # Initialize and update submodules
            git submodule update --init --recursive

            # Check out master branch and pull latest for all submodules
            git submodule foreach --recursive git checkout master
            git submodule foreach --recursive git pull origin master

  create_env_file:
    runs-on: ubuntu-latest

    steps:
      - name: create file
        run: |
          cat <<EOT > .env
          DJANGO_SUPERUSER_USERNAME=${{ vars.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ vars.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUPERUSER_EMAIL=${{ vars.DJANGO_SUPERUSER_EMAIL }}
          API_URL=${{ vars.API_URL }}
          EOT

      - name: SCP .env file to the server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .env
          target: ${{secrets.PROJECT_PATH}}

  trigger_frontend:
    runs-on: ubuntu-latest
    needs: deploy_main_repo

    steps:
      - name: Trigger Downstream for frontend
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: JohnTwiiX/conduit-frontend
          token: ${{ secrets.PAT }}
          event-type: trigger-build

  trigger_backend:
    runs-on: ubuntu-latest
    needs: deploy_main_repo

    steps:
      - name: Trigger Downstream for backend
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: JohnTwiiX/conduit-backend
          token: ${{ secrets.PAT }}
          event-type: trigger-build
